// ✅ EchoScript.AI — Language Options for Transcription

export const languageOptions = [
  { value: "ar", label: "العربية (Arabic)" },
  { value: "bn", label: "বাংলা (Bengali)" },
  { value: "cs", label: "Čeština (Czech)" },
  { value: "da", label: "Dansk (Danish)" },
  { value: "de", label: "Deutsch (German)" },
  { value: "el", label: "Ελληνικά (Greek)" },
  { value: "en", label: "English" },
  { value: "es", label: "Español (Spanish)" },
  { value: "fa", label: "فارسی (Persian)" },
  { value: "fi", label: "Suomi (Finnish)" },
  { value: "fr", label: "Français (French)" },
  { value: "he", label: "עברית (Hebrew)" },
  { value: "hi", label: "हिन्दी (Hindi)" },
  { value: "hu", label: "Magyar (Hungarian)" },
  { value: "id", label: "Bahasa Indonesia" },
  { value: "it", label: "Italiano (Italian)" },
  { value: "ja", label: "日本語 (Japanese)" },
  { value: "ko", label: "한국어 (Korean)" },
  { value: "ms", label: "Bahasa Melayu (Malay)" },
  { value: "nl", label: "Nederlands (Dutch)" },
  { value: "no", label: "Norsk (Norwegian)" },
  { value: "pl", label: "Polski (Polish)" },
  { value: "pt", label: "Português (Portuguese)" },
  { value: "ro", label: "Română (Romanian)" },
  { value: "ru", label: "Русский (Russian)" },
  { value: "sv", label: "Svenska (Swedish)" },
  { value: "th", label: "ไทย (Thai)" },
  { value: "tr", label: "Türkçe (Turkish)" },
  { value: "uk", label: "Українська (Ukrainian)" },
  { value: "vi", label: "Tiếng Việt (Vietnamese)" },
  { value: "zh", label: "中文 (Chinese)" },
];
